version: '3'
services:
  # 서비스 명
  mysql:
    # 사용할 이미지
    image: mysql:8.0

    # 컨테이너 실행 시 재시작
    restart: always

    # 컨테이너명 설정
    container_name: CommerceDB

    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '${DATABASE_PORT}:3306'

    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'

    # 명령어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
